python_requirement(
    name="pydantic-1",
    requirements=["pydantic~=1.0"],
    resolve="pydantic-1",
)
python_requirement(
    name="pydantic-2",
    requirements=["pydantic~=2.0"],
    resolve="pydantic-2",
)
