[GLOBAL]
pants_version = "2.18.0"
backend_packages = [
    "pants.backend.python",
]

[python]
interpreter_constraints = ["==3.11.*"]
enable_resolves = true
default_resolve = "pydantic-1"

[python.resolves]
pydantic-1 = "lockfiles/pydantic-1.lock"
pydantic-2 = "lockfiles/pydantic-2.lock"
